apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations: {}
  name: 
  namespace: 
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          name: 
        spec:
          containers:
          - name: runner
            image: {IMAGE_HERE}
            imagePullPolicy: IfNotPresent 
            env:
              - name: DATABASE_HOST
                value: ""
              - name: PROCEDURE
                value: ""
              - name: MYSQL_USER
                value: ""
              - name: MYSQL_PASSWORD
                valueFrom:                                                                                                                                                                          
                  secretKeyRef:                                                                                                                                                                     
                    key: password 
                    name: mysql
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '*/1 * * * *'
  successfulJobsHistoryLimit: 5
  suspend: false
